package com.study.board.mybatis.mapper;

import com.study.board.entity.Auth;
import com.study.board.entity.AuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    long countByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    int deleteByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    @Delete({
        "delete from Auth",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    @Insert({
        "insert into Auth (id, username, ",
        "password)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR})"
    })
    int insert(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    int insertSelective(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    List<Auth> selectByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    @Select({
        "select",
        "id, username, password",
        "from Auth",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.study.board.mybatis.mapper.AuthMapper.BaseResultMap")
    Auth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    int updateByExampleSelective(@Param("record") Auth record, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    int updateByExample(@Param("record") Auth record, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    int updateByPrimaryKeySelective(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Auth
     *
     * @mbg.generated Tue Nov 03 16:04:49 JST 2020
     */
    @Update({
        "update Auth",
        "set username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Auth record);
}